apiVersion: v1
kind: Service
metadata:
  name: calcbackendsvc
  labels:
    name: calcbackendsvc
    app: calculator  
spec:
  ports:
  - port: 80
    name: calcbackend
    targetPort: 80
  selector:
    name: calcbackend
    app: calculator